- id: oilers_goal
  alias: Oilers Goal
  trigger:
  - platform: event
    event_type: goal
    event_data:
      team_name: "Edmonton Oilers"
  condition: []
  action:
  - delay: "00:00:{{ states.input_number.goalfeed.state | int }}"
  - data:
      entity_id: light.goal_light
    service: light.turn_on
